# Generated by Django 5.2.1 on 2025-06-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата рейса')),
                ('customer', models.CharField(max_length=255, verbose_name='Заказчик')),
                ('truck_number', models.CharField(max_length=50, verbose_name='Номер машины')),
                ('driver_name', models.CharField(max_length=255, verbose_name='ФИО водителя')),
                ('direction', models.CharField(max_length=255, verbose_name='Направление')),
                ('route_sheet', models.TextField(blank=True, verbose_name='Маршрутный лист')),
                ('tonnage', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Тоннаж авто')),
                ('distance', models.PositiveIntegerField(verbose_name='Километраж')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Вес')),
                ('pallets', models.PositiveIntegerField(verbose_name='Палеты')),
                ('points', models.PositiveIntegerField(verbose_name='Количество точек')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость рейса')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
