# Generated by Django 5.2.1 on 2025-06-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255)),
                ('direction', models.CharField(default='любой', max_length=255)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_point', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pallet_based_prices', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
