# Generated by Django 5.2.1 on 2025-06-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_tariff_delete_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterField(
            model_name='tariff',
            name='base_price',
            field=models.IntegerField(default=0, verbose_name='Базовая ставка'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='customer',
            field=models.CharField(max_length=255, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='direction',
            field=models.CharField(default='любой', max_length=255, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='pallet_based_prices',
            field=models.JSONField(blank=True, null=True, verbose_name='Цены по количеству палет'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_per_km',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена за км'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_per_point',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена за точку'),
        ),
    ]
