# Generated by Django 5.2.1 on 2025-06-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_tariff_options_alter_tariff_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='tonnage_based_prices',
            field=models.JSONField(blank=True, null=True, verbose_name='Цены по тоннажу машины'),
        ),
    ]
