# Generated by Django 5.2.1 on 2025-06-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_tariff_tonnage_based_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='tonnage',
            field=models.PositiveIntegerField(verbose_name='Тоннаж авто'),
        ),
    ]
