# Generated by Django 5.2.1 on 2025-06-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_driver_truck_remove_trip_driver_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name': 'Рейс', 'verbose_name_plural': 'Рейсы'},
        ),
    ]
