# Generated by Django 5.2.1 on 2025-06-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_alter_trip_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Километраж'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pallets',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Палеты'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='points',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество точек'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route_sheet',
            field=models.TextField(blank=True, null=True, verbose_name='Маршрутный лист'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='tonnage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Тоннаж авто'),
        ),
    ]
