# Generated by Django 5.2.1 on 2025-06-21 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trips.customer', verbose_name='Заказчик'),
        ),
    ]
