# Generated by Django 5.2.1 on 2025-06-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_alter_trip_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='extra_point_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена за каждую точку сверх лимита'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='points_threshold',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Макс. кол-во точек по фикс. ставке'),
        ),
    ]
