# Generated by Django 5.2.1 on 2025-06-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_tariff_extra_point_price_tariff_points_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='extra_point_price',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='points_threshold',
        ),
        migrations.AddField(
            model_name='tariff',
            name='extra_point_price_per_tonnage',
            field=models.JSONField(blank=True, null=True, verbose_name='Цена за каждую точку сверх лимита'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='max_points_per_tonnage',
            field=models.JSONField(blank=True, null=True, verbose_name='Макс. кол-во точек по фикс. ставке'),
        ),
    ]
