# Generated by Django 5.2.1 on 2025-06-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_remove_tariff_extra_point_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='point_limit_per_tonnage',
            field=models.JSONField(blank=True, null=True, verbose_name='Лимит точек по тоннажу'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='extra_point_price_per_tonnage',
            field=models.JSONField(blank=True, null=True, verbose_name='Цена за доп. точку по тоннажу'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='max_points_per_tonnage',
            field=models.JSONField(blank=True, null=True, verbose_name='Максимум точек по тоннажу (для расчёта доплаты)'),
        ),
    ]
