# Generated by Django 5.2.1 on 2025-06-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_tariff_point_limit_per_tonnage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='point_limit_per_tonnage',
        ),
    ]
