# Generated by Django 5.2.3 on 2025-06-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_remove_tariff_point_limit_per_tonnage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
    ]
